Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "provision/provision.sh"

  nodes = {
    "control" => "192.168.56.10",
    "worker1" => "192.168.56.11",
    "worker2" => "192.168.56.12"
  }

  nodes.each do |name, ip|
    config.vm.define name do |node|
      node.vm.box = "bento/ubuntu-22.04"
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip

      node.vm.provider "vmware_desktop" do |v|
        v.memory = 2048
        v.cpus = 2
        v.linked_clone = false
      end
    end
  end
end